# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json
services:
  api:
    image: weshigbee/course-microsvcs-api
    build:
      context: ./catalog-api/src
      platforms:
        - "linux/arm/v7"
        - "linux/arm64"
        - "linux/amd64"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=library_catalog;Username=library_user;Password=library_pass"
      ASPNETCORE_ENVIRONMENT: Production

  db:
    image: postgres:17.2
    environment:
      - POSTGRES_DB=library_catalog
      - POSTGRES_USER=library_user
      - POSTGRES_PASSWORD=library_pass
      # setting these means when you exec in, psql works without any args:
      - PGDATABASE=library_catalog
      - PGUSER=library_user
      - PGPASSWORD=library_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./db/init:/docker-entrypoint-initdb.d
    deploy:
      placement:
        constraints:
          - node.hostname==pi3.lan
    configs:
      - source: init_sql
        target: /docker-entrypoint-initdb.d/init.sql

  web:
    image: weshigbee/course-microsvcs-web
    build:
      context: ./web
      platforms:
        - "linux/arm/v7"
        - "linux/arm64"
        - "linux/amd64"
    ports:
      - "8080:80"

volumes:
  postgres_data:

configs:
  init_sql:
    file: ./db/init/01-init.sql
